const companyGroups = [
  "Support Group",
  "Development Group",
  "Quality Assurance Group",
  "Human Resources",
  "Marketing Team",
  "Sales Team",
  "Finance Department",
  "IT Operations",
  "Customer Service",
  "Legal Department",
  "Research and Development",
  "Product Management",
  "Design Team",
  "Executive Management",
  "Logistics and Supply Chain",
];
